-- AlterTable
ALTER TABLE `Category` ADD COLUMN `color` VARCHAR(191) NULL,
    ADD COLUMN `icon` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Post` ADD COLUMN `color` VARCHAR(191) NULL,
    ADD COLUMN `icon` VARCHAR(191) NULL,
    ADD COLUMN `noAiSummary` BOOLEAN NOT NULL DEFAULT false;
