const playList = [
  { link: "T_MYHHb1Ib0", bgImage: "lostark", title: "모코코 Remix " },
  { link: "ffI42h6L_KI", bgImage: "lostark", title: "모코콩 아일랜드 (Mokokong Island) " },
  { link: "9iw2NJyV6dg", bgImage: "lostark", title: "모코코마을 (Mokoko Village)" },
  { link: "gnm1_MFcwm0", bgImage: "lostark", title: "별빛 등대의 섬(jazz Ver.) (Star Light Island jazz Ver.)" },
  { link: "jZwv83Stl60", bgImage: "lostark", title: "라제니스의 노래 (Song of Lazernes) " },
  { link: "ENB-BSYCg1c", bgImage: "lostark", title: "Sweet Dreams, My Dear - 소향(SoHyang)" },
  { link: "H-Ngv9OVqP8", bgImage: "lostark", title: "아리안오브 (Aryanorb)" },
  { link: "WZgiTJova1Q", bgImage: "lostark", title: "위대한 기억의 오르골" },
  { link: "7F4QS5OWlG8", bgImage: "lostark", title: "별모래 해변" },
  { link: "P0qtL25eD7Q", bgImage: "lostark", title: "그대 기억 하나요?" },
  { link: "PwAD4uVeDgU", bgImage: "lostark", title: "해상 낙원 페이토" },
  { link: "wsEq1itieOo", bgImage: "lostark", title: "기에나의 바다" },
  { link: "btM_zzqtt90", bgImage: "lostark", title: "리베하임" },
  { link: "YdMZeIdpnNw", bgImage: "lostark", title: "로맨틱 웨폰" },
  { link: "8sxhDyBlpCk", bgImage: "lostark", title: "Dreaming Your Melody" },
  { link: "axmFywZvrto", bgImage: "lostark", title: "30년 전의 나에게 (To Me, My Childhood)" },
  { link: "_jg3wNlGO0Y", bgImage: "lostark", title: "Dear Friends - 효린(HYOLYN) " },
  { link: "_AnFWUowPfM", bgImage: "lostark", title: "반짝이는 바람 (Twinkling Winds)" },
  { link: "loevvMFPjms", bgImage: "lostark", title: "메리 아르고스마스! (Merry Argosmas!) " },
  { link: "i3R_YwJQWBk", bgImage: "lostark", title: "행운의 아크랜드 (Ark Wonderland)" },
  { link: "hs-tG_JvMgA", bgImage: "lostark", title: "욕망의 무도회 (Ball of Desire) " },
  { link: "v2h0Qy1oCi0", bgImage: "lostark", title: "여름밤의 축제 섬 (Summer Night Festival) " },
  { link: "fzfAaoNrbb8", bgImage: "lostark", title: "피어나는 불꽃의 순간 (A Moment of Blooming Fires)" },
  { link: "m3aJ3nKyfFQ", bgImage: "lostark", title: "새벽을 지키는 땅 (Land that Guards the Dawn)" },
  { link: "z6PKIr9AAVg", bgImage: "lostark", title: "모두의 소원을 담아 (A Tearful For all good Wishes)" },
  { link: "RlQbmF8DiU0", bgImage: "lostark", title: "다시, 겨울방학 (Again, Winter Vacation) - feat. 보라미유" },
  { link: "EG-ki5AtNno", bgImage: "lostark", title: "겨울 캠핑 (Winter Camping)" },
  { link: "dTuVWfbnPKk", bgImage: "lostark", title: "모여드는 작은 빛 (Little Light that Gathers)" },
  { link: "v8aX4sQjSpU", bgImage: "mapelstory", title: "The Raindrop Flower [MapleStory Symphony in Budapest] / 메이플스토리 오케스트라 앨범" },
  { link: "ODOEt3_A6qM", bgImage: "mapelstory", title: "The Queen's Garden [MapleStory Symphony in Budapest] / 메이플스토리 오케스트라 앨범" },
  { link: "kizi98UD5ak", bgImage: "mapelstory", title: "The Raindrop Flower (Jazz Ver.)｜메이플스토리 (MapleStory) OST : Jazz of Maple" },
  { link: "NKt5NMCyZvg", bgImage: "mapelstory", title: "The Tune of The Azure Light [MapleStory Symphony in Budapest] / 메이플스토리 오케스트라 앨범" },
  { link: "WihYiw2S8hU", bgImage: "mapelstory", title: "Start The Adventure (Orchestral Ver.) [MapleStory Symphony in Budapest] / 메이플스토리 오케스트라 앨범" },
  { link: "SWOEVxpuiqE", bgImage: "mapelstory", title: "MapleStory Symphony in Budapest - When The Morning Comes" },
  { link: "r2cx06CLBNA", bgImage: "kartrider", title: "카트라이더 대저택 풀 오케스트라 Kartrider Mansion Dance Battle OST" },
  { link: "FzH8gXzB4Xw", bgImage: "onepiece", title: '원피스 "우리의 꿈" 오케스트라 편곡 버전 (with Cubase)' },
  { link: "RRHw3rvTnxI", bgImage: "onepiece", title: "세상 저 끝까지 - 원피스 극장판" },
  { link: "wFkRpaldkh4", bgImage: "unchartedwartersonline", title: "Uncharted Waters Online OST - Login title" },
  { link: "vMtJnEQ59Sg", bgImage: "unchartedwartersonline", title: "Uncharted Waters Online OST - London" },
  { link: "ER0olOF_LKE", bgImage: "unchartedwartersonline", title: "Uncharted waters Online OST- Apennines by land (Venice)" },
  { link: "7ICS-FjUKgs", bgImage: "unchartedwartersonline", title: "Uncharted waters Online OST- 마르세이유" },
  { link: "yWZkOtriVVY", bgImage: "lostark", title: "10_레온하트 (크리스마스버전) (Leonhart X-mas Ver.) / 로스트아크" },
];

export { playList };
